## Bài 1. Tạo Tensor cơ bản
Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [17]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


**Yêu cầu**: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

**Kết quả**:
- Kích thước: 2x3
- Số chiều: 2 chiều (gồm 2 hàng và 3 cột)
- Kiểu dữ liệu: số nguyên (int)

## Bài 2. Tạo các Tensor thường dùng
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [18]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.6564, 0.2357, 0.0230, 0.2447],
        [0.2288, 0.0760, 0.0233, 0.6651],
        [0.5633, 0.0643, 0.6013, 0.8193]])
tensor([[ 0.0746, -0.4413,  0.1134,  0.9300],
        [ 1.2199, -1.2352,  0.1010, -0.2774],
        [ 0.3536, -0.3021, -0.0517, -0.5805]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


**Yêu cầu**: 
- Nhận xét sự khác nhau giữa torch.rand() và torch.randn().
- Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

**Kết quả**:
- torch.rand(): Sử dụng phân phối đều (**[0, 1)**), các giá trị trong ma trận chỉ nằm trong khoảng 0 đến 1, không chứa giá trị âm.
- torch.randn(): Sử dụng phân phối Gauss(**(-∞, +∞)**), các giá trị trong ma trận tập trung nhiều quanh 0, càng xa 0 càng ít xuất hiện và có chứa giá trị âm.

In [19]:
# Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.
f = torch.full((5, 5), 10)

print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [20]:
import torch
a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3


**Yêu cầu**: Giải thích ý nghĩa của torch.Size([2, 3, 4]).

**Kết quả**:
- Có 2 ma trận rỗng có kích thước 3x4.

## Bài 4. Slicing và Indexing
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [21]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 0.1507, -1.8328, -1.6220, -0.2177,  0.9911],
         [ 1.0336,  0.3107,  0.1657,  0.9995, -0.2127],
         [ 0.6844,  0.9617,  1.3829,  0.7071, -0.0508],
         [-0.1017, -0.2587,  1.9031, -0.4535, -0.3880]],

        [[-0.9257,  0.2646, -0.7212, -0.5850,  0.8321],
         [-0.4802, -0.3190,  0.6407,  0.9775, -0.2529],
         [-0.1893, -0.3397, -0.0297, -1.0659, -0.9922],
         [ 0.6998, -0.1418, -0.3899, -0.1365,  3.0168]],

        [[ 0.3761, -0.9744,  0.5913,  1.0597, -0.0846],
         [ 1.3485,  2.4708,  0.6384, -0.6667,  1.5369],
         [ 0.4540, -0.0232,  0.3527,  0.1497, -0.3582],
         [-0.1223,  0.5231, -0.3172,  0.7384, -0.4826]]])

Tensor a[1]:
tensor([[-0.9257,  0.2646, -0.7212, -0.5850,  0.8321],
        [-0.4802, -0.3190,  0.6407,  0.9775, -0.2529],
        [-0.1893, -0.3397, -0.0297, -1.0659, -0.9922],
        [ 0.6998, -0.1418, -0.3899, -0.1365,  3.0168]])

Tensor a[1:, 2:4]:
tensor([[[-0.1893, -0.3397, -0.0297, -1.0659, -0.9

**Yêu cầu**: 
- Cho biết shape của a[1] và a[1:, 2:4].
- Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

**Kết quả**:
- Shape: 
    - a[1]: ma trận 4x5
    - a[1:, 2:4]: 2 ma trận 2x5

In [5]:
#Shape
print ("Shape a[1]: " ,(a[1].shape))

print ("Shape a[1:, 2:4]: " ,(a[1:, 2:4].shape))


Shape a[1]:  torch.Size([4])
Shape a[1:, 2:4]:  torch.Size([2, 2])


In [24]:
# Lấy hai phần tử cuối cùng trên chiều thứ ba
a[:, :, -2:]

tensor([[[-0.2177,  0.9911],
         [ 0.9995, -0.2127],
         [ 0.7071, -0.0508],
         [-0.4535, -0.3880]],

        [[-0.5850,  0.8321],
         [ 0.9775, -0.2529],
         [-1.0659, -0.9922],
         [-0.1365,  3.0168]],

        [[ 1.0597, -0.0846],
         [-0.6667,  1.5369],
         [ 0.1497, -0.3582],
         [ 0.7384, -0.4826]]])

## Bài 5. Reshape và Flatten
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [1]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.0294, -1.1352,  1.4799,  1.6398],
        [ 0.1498,  1.9367,  0.8845,  1.4105],
        [ 0.7305,  1.1645,  0.8977,  0.4912]])

Flatten:
tensor([ 0.0294, -1.1352,  1.4799,  1.6398,  0.1498,  1.9367,  0.8845,  1.4105,
         0.7305,  1.1645,  0.8977,  0.4912])

Reshape to 3 x 2 x 2:
tensor([[[ 0.0294, -1.1352],
         [ 1.4799,  1.6398]],

        [[ 0.1498,  1.9367],
         [ 0.8845,  1.4105]],

        [[ 0.7305,  1.1645],
         [ 0.8977,  0.4912]]])


**Yêu cầu**: 
- Kiểm tra số phần tử trước và sau khi reshape.
- Thử reshape Tensor thành kích thước 2 × 6.

**Kết quả**:
- Số phần tử trước reshape: 12 phần tử, Số phần tử sau reshape: 3 ma trận đều có 4 phần tử.

In [6]:
# số phần tử trước và sau khi reshape.
print("Trước reshape:", a.shape)
print("Sau reshape:", a.reshape(3, 2, 2).shape)

Trước reshape: torch.Size([3, 4])
Sau reshape: torch.Size([3, 2, 2])


In [7]:
# reshape Tensor thành kích thước 2 × 6
print(a.reshape( 2, 6))

tensor([[ 0.0294, -1.1352,  1.4799,  1.6398,  0.1498,  1.9367],
        [ 0.8845,  1.4105,  0.7305,  1.1645,  0.8977,  0.4912]])


## Bài 6. Phép toán và nhân ma trận
Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [8]:
import torch

a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 0.4173,  0.7319, -1.0494],
        [ 2.0330, -1.5014,  1.7079]])
b:
tensor([[ 0.4472,  0.6720,  0.9830],
        [-1.1775, -0.2348, -1.0270]])

a + b:
tensor([[ 0.8646,  1.4039, -0.0663],
        [ 0.8556, -1.7361,  0.6809]])

a / b:
tensor([[ 0.9331,  1.0891, -1.0674],
        [-1.7266,  6.3952, -1.6630]])

a^2:
tensor([[0.1742, 0.5357, 1.1011],
        [4.1332, 2.2541, 2.9168]])

Matrix multiplication:
tensor([[-0.3531,  0.4145],
        [ 1.5793, -3.7953]])


**Yêu cầu**: 
- Phân biệt phép toán a * b với a @ b.T.
- Cho biết shape của kết quả a @ b.T.

**Kết quả**:
- a*b: thực hiện phép nhân từng phần tử tương ứng của hai ma trận nên kết quả có shape (2,3).
- a @ b.T: thực hiện phép nhân ma trận, với b.T có shape (3,2) nên kết quả có shape (2,2)
- Shape a @ b.T: ma trận 2x2

In [12]:
# Ma trận a*b
print(a*b)

# Ma trận a @ b.T
print(a @ b.T)

#Shape a @ b.T
print("Shape a @ b.T: " ,(a @ b.T).shape)

tensor([[ 0.1867,  0.4918, -1.0316],
        [-2.3938,  0.3525, -1.7540]])
tensor([[-0.3531,  0.4145],
        [ 1.5793, -3.7953]])
Shape a @ b.T:  torch.Size([2, 2])


## Bài 7. Các hàm thống kê trên Tensor
Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [13]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.2428, -2.0160, -1.1070, -0.3504],
        [-0.3763,  0.1236, -0.5444, -0.7849],
        [-0.4414, -1.3558,  0.2760,  1.2377]])

Mean:
tensor([-0.1916, -1.0827, -0.4585,  0.0341])

Standard deviation:
tensor([0.3777, 1.0956, 0.6955, 1.0647])

Cumulative sum:
tensor([[ 0.2428, -2.0160, -1.1070, -0.3504],
        [-0.1335, -1.8924, -1.6515, -1.1353],
        [-0.5749, -3.2482, -1.3755,  0.1023]])


**Yêu cầu**: 
- Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

**Kết quả**:
- Dim = 0: tính theo từng cột, nên mean, std có 4 giá trị và Cumulative sum tính từ trên xuống.
- Dim = 1: tính theo từng hàng, nên mean, std có 3 giá trị và Cumulative sum tính từ trái sáng phải.

In [ ]:
print(torch.mean(a, dim=1))

print("\nStandard deviation:")
print(torch.std(a, dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([-0.8077, -0.3955, -0.0709])

Standard deviation:
tensor([0.9768, 0.3846, 1.0986])

Cumulative sum:
tensor([[ 0.2428, -1.7732, -2.8803, -3.2307],
        [-0.3763, -0.2527, -0.7972, -1.5821],
        [-0.4414, -1.7972, -1.5212, -0.2836]])


## Bài 8. Autograd cơ bản
Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [15]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


**Yêu cầu**: 
- Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.
- Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

**Kết quả**:
- Đạo hàm của y = x^2 tại x = 3.6: y = 2x = 7.2
- So sánh: bằng nhau

- Đạo hàm y = 3x^2 + 2x + 1 = 6x + 2 = 23.6
- Gradient của y = 3*x**2 + 2*x + 1 = 23.6, kết quả bằng nhau

In [16]:
x = torch.tensor(
3.6,
requires_grad=True
)
y = 3*x**2 + 2*x + 1
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


## Bài 9. Gradient Descent tìm hệ số đa thức
Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [17]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
X * X,
X,
np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-1.8516],
        [ 0.9187],
        [-0.0345]], requires_grad=True)
Learned coefficients:
tensor([[1.0014],
        [2.0022],
        [2.8323]], requires_grad=True)


**Yêu cầu**: 
- So sánh ba hệ số học được với [1, 2, 3].
- Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().

**Kết quả**:
- 3 hệ số học được có giá trị gần với hệ số ban đầu nhưng không bằng vì MSE tiệm cận về 0.
- optimizer.zero_grad(): Reset toàn bộ đạo hàm của các biến hiện tại về ban đầu trước khi tính đạo hàm mới.
- mse.backward(): Tính đạo hàm của hàm mất mát (MSE) theo các hệ số w. 
- optimizer.step(): cập nhật hệ số w theo thuật toán NAdam để giảm sai số MSE.

## Bài 10. Giải hệ phương trình bằng Autograd
Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [18]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)

print("C =", C)
print("D =", D)

A = tensor(4.6465, requires_grad=True)
B = tensor(4.3534, requires_grad=True)
C = tensor(3.3535, requires_grad=True)
D = tensor(2.3534, requires_grad=True)


**Yêu cầu**: 
- Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.
- Nhận xét vì sao bài toán có thể có nhiều nghiệm.

**Kết quả**:
-  Kiểm tra nghiệm thu được: A+B=8.9999, C-D=1.0001, A+C=8.0000, B-D=2.0000

    Kết luận: Sai số rất nhỏ
- Nhận xét: Vì 1 trong 4 phương trình phụ thuộc vào các phương trình còn lại (4 ẩn nhưng chỉ có 3 pt độc lập).

## Bài 11: Viết chương trình PyTorch để thực hiện các yêu cầu sau:

**Yêu cầu**:
- Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.
- Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.
- Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.
- Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [36]:
# Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.
X = torch.randn(24)
print("Tensor X:")
print(X)

print("Tensor 4x6")
print(X.reshape(4, 6))

print("Tensor 2x12")
print(X.reshape(2, 12))

print("Tensor 2x3x4")
print(X.reshape(2, 3, 4))

Tensor X:
tensor([ 0.4969,  0.1460, -0.7639, -0.8069,  0.5555, -0.9160, -0.3864, -0.9593,
        -1.1049,  0.8254,  0.3225, -0.6399,  0.5124,  0.7560, -0.3735, -0.6824,
         0.4968,  1.2440, -0.1487, -0.6026,  0.9703,  0.3479,  2.0880,  1.0546])
Tensor 4x6
tensor([[ 0.4969,  0.1460, -0.7639, -0.8069,  0.5555, -0.9160],
        [-0.3864, -0.9593, -1.1049,  0.8254,  0.3225, -0.6399],
        [ 0.5124,  0.7560, -0.3735, -0.6824,  0.4968,  1.2440],
        [-0.1487, -0.6026,  0.9703,  0.3479,  2.0880,  1.0546]])
Tensor 2x12
tensor([[ 0.4969,  0.1460, -0.7639, -0.8069,  0.5555, -0.9160, -0.3864, -0.9593,
         -1.1049,  0.8254,  0.3225, -0.6399],
        [ 0.5124,  0.7560, -0.3735, -0.6824,  0.4968,  1.2440, -0.1487, -0.6026,
          0.9703,  0.3479,  2.0880,  1.0546]])
Tensor 2x3x4
tensor([[[ 0.4969,  0.1460, -0.7639, -0.8069],
         [ 0.5555, -0.9160, -0.3864, -0.9593],
         [-1.1049,  0.8254,  0.3225, -0.6399]],

        [[ 0.5124,  0.7560, -0.3735, -0.6824],
         [ 

In [39]:
# Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A =", A)
print("B =", B)

print("\nA + B:", A + B)
print("A * B:", A * B)
print("A / B:", A / B)

print("Trung bình theo cột của A:", A.mean(dim=0))
print("Độ lệch chuẩn theo cột của A:", A.std(dim=0))

A = tensor([[ 0.0352, -0.4872,  1.7132, -0.4583],
        [ 1.0278, -0.1278,  0.5428, -0.9981],
        [-0.0067,  1.0875, -0.2630,  0.1779]])
B = tensor([[ 0.5839,  0.4976,  1.9256, -0.5047],
        [ 0.4847,  0.5146,  1.9256, -0.2380],
        [-0.0819, -0.3730, -2.2113,  1.4797]])

A + B: tensor([[ 0.6191,  0.0104,  3.6388, -0.9630],
        [ 1.5125,  0.3868,  2.4683, -1.2361],
        [-0.0886,  0.7145, -2.4742,  1.6576]])
A * B: tensor([[ 2.0560e-02, -2.4244e-01,  3.2990e+00,  2.3129e-01],
        [ 4.9815e-01, -6.5752e-02,  1.0451e+00,  2.3752e-01],
        [ 5.4959e-04, -4.0567e-01,  5.8150e-01,  2.6322e-01]])
A / B: tensor([[ 0.0603, -0.9790,  0.8897,  0.9082],
        [ 2.1207, -0.2483,  0.2819,  4.1946],
        [ 0.0820, -2.9156,  0.1189,  0.1202]])
Trung bình theo cột của A: tensor([ 0.3521,  0.1575,  0.6643, -0.4262])
Độ lệch chuẩn theo cột của A: tensor([0.5856, 0.8252, 0.9937, 0.5887])


In [ ]:
#Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5*x + 3
y.backward()
print("x=",x)
print("y=",y)
print("x.grad:", x.grad)


# y = 2x^2 - 5x + 3 => dy/dx = 4x + 5. 
# Tại x = 2, dy/dx = 4*2 + 5 = 13. 
# KL: bằng nhau

x= tensor(2., requires_grad=True)
y= tensor(21., grad_fn=<AddBackward0>)
x.grad: tensor(13.)


In [ ]:
# Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.
import numpy as np
import torch

polynomial = np.poly1d([2, -3, 5])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
X * X,
X,
np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.2890],
        [-0.0745],
        [ 1.3110]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0145],
        [-3.0065],
        [ 3.9068]], requires_grad=True)


**Hệ số tìm được**: 
        [ 2.1294],
        [-3.0258],
        [ 2.4579]

Có thể các nguyên nhân dẫn đến w3 k gần bằng 5 vì: epoch, N chưa đủ, learning rate 0.01 chưa phù hợp, X có độ lớn tương đối lớn, 